// alert.js
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

// auth.js
export const USER_LOADED = "USER_LOADED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const FORGET_PASSWORD = "FORGET_PASSWORD";
export const RECOVERY_PASSWORD = "RECOVERY_PASSWORD";
export const CHANGE_PROFILE = "CHANGE_PROFILE";
export const AUTH_ERROR = "AUTH_ERROR";

// data.js
export const REFRESH_DATA = "REFRESH_DATA";
export const REFRESH_DATAATTENDANCE = "REFRESH_DATAATTENDANCE"
export const LOAD_DATA = "LOAD_DATA";
export const LOAD_DATAUSER = "LOAD_DATAUSER";
export const LOAD_DATADAILYTASK = "LOAD_DATADAILYTASK";
export const LOAD_DATAROLE = "LOAD_DATAROLE";
export const LOAD_DATACOMPANY = "LOAD_DATACOMPANY";
export const LOAD_DATADIVISI = "LOAD_DATADIVISI";
export const LOAD_DATAPOSISI = "LOAD_DATAPOSISI";
export const LOAD_DATAKALENDAR = "LOAD_DATAKALENDAR";
export const LOAD_DATASHIFT = "LOAD_DATASHIFT";
export const LOAD_DATAWIFI = "LOAD_DATAWIFI";
export const LOAD_DATAATTENDANCE = "LOAD_DATAATTENDANCE";
export const LOAD_DATALEAVE = "LOAD_DATALEAVE";
export const LOAD_DATAMODULE = "LOAD_DATAMODULE";
export const ADD_DATA = "ADD_DATA";
export const EDIT_DATA = "EDIT_DATA";
export const DELETE_DATA = "DELETE_DATA";
export const DELETE_DATAUSER = "DELETE_DATAUSER";
export const DELETE_DATADIVISI = "DELETE_DATADIVISI";
export const DELETE_DATADAILYTASK = "DELETE_DATADAILYTASK";
export const DELETE_DATAPOSISI = "DELETE_DATAPOSISI";
export const DELETE_DATAKALENDAR = "DELETE_DATAKALENDAR";
export const DELETE_DATASHIFT = "DELETE_DATASHIFT";
export const DELETE_DATAWIFI = "DELETE_DATAWIFI";
export const DELETE_DATAROLE = "DELETE_DATAROLE";
export const DELETE_DATAATTENDANCE = "DELETE_DATAATENDANCE";
export const DELETE_DATALEAVE = "DELETE_DATALEAVE";
export const DELETE_DATAMODULE = "DELETE_DATAMODULE";
export const EXPORT_DATA = "EXPORT_DATA";
export const UPLOAD_DATA = "UPLOAD_DATA";
export const CRUD_FAIL = "CRUD_FAIL";

// master.js
export const LOAD_USER = "LOAD_USER";
export const LOAD_ROLE = "LOAD_ROLE";
export const LOAD_MODULE = "LOAD_MODULE";


export const SYNC_DATE = "SYNC_DATE";


export const ATTENDANCE_WORKINGHOUR = "ATTENDANCE_WORKINGHOUR";
export const ATTENDANCE_HOUR = "ATTENDANCE_HOUR";

export const LOAD_POSITION = "LOAD_POSITION";
export const LOAD_COMPANY = "LOAD_COMPANY";
export const LOAD_DIVISION = "LOAD_DIVISION";
export const LOAD_SHIFT = "LOAD_SHIFT";
export const LOAD_ATTENDANCE = "LOAD_ATTENDANCE";
export const LOAD_CALENDAR = "LOAD_CALENDAR";